### PR TITLE
Puts a space between accounts when using SHOWMYACCOUNTS.

### PR DESCRIPTION
**Pull request by JaneMansell**
Previously display was: Main: 800Savings: 200. Now there is a space between:
image

I would have liked to make them into a vertical list but because of how the existing code works this would have been a lot more work.

### CODE REVIEW

**Comment by bairdj** [comment]
Would a new line be clearer?

**Comment by JaneMansell** [comment]
@bairdj Is there an easy way to do a new line? The only way I could think to do it was to take it out of the switch and into NewBankClientHandler.java as an array and print the array there but that seems a lot of code for aesthetics.

**Comment by bairdj** [comment]
Yes you can use \n to insert a new line

**Comment by JaneMansell** [comment]
I knew we could do that with printf but I didn't know we could do it with println. I will give it a go.

**Comment by JaneMansell** [comment]
I have updated it to print in a list:
image

**Pull request merged**
